### ISSUE TITLE
 Unable to compose the engine  java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by datacommunitydata** [MasayukiSuda/Mp4Composer-android#118]
working fine on other devices but raising this issue on infinix device
 Unable to compose the engine
                                                                                                    java.lang.IllegalArgumentException
                                                                                                    	at android.media.MediaCodec.native_configure(Native Method)
                                                                                                    	at android.media.MediaCodec.configure(MediaCodec.java:2127)
                                                                                                    	at android.media.MediaCodec.configure(MediaCodec.java:2043)
                                                                                                    	at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:78)
                                                                                                    	at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:124)
                                                                                                    	at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:312)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
                                                                                                    	at java.lang.Thread.run(Thread.java:923)

**Comment by pspsingh677** [comment]
i am also getting same issue in android 14 devices but did not find any solution. @datacommunitydata have you find any solution?
