### ISSUE TITLE
cannot save video with filter

### ISSUE THREAD

**Issue by mikkipastel** [MasayukiSuda/Mp4Composer-android#12]
Hello,

I have some problem for save video with filter and I don’t sure what cause for this problem then I discuss with you about this for find solution to solve this.

```
android.media.MediaCodec$CodecException: Error 0xfffffc03
  at android.media.MediaCodec.native_configure(Native Method)
  at android.media.MediaCodec.configure(MediaCodec.java:577)
  at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:86)
  at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:102)
  at com.daasuu.mp4compose.composer.Mp4Composer$1.run(Mp4Composer.java:158)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
```

**Comment by creativecoderbee** [comment]
have same issue. u got solution ?

**Comment by MasayukiSuda** [comment]
Check width, height, bitrate and video format. Maybe you have specified a video format that MediaCodec does not support
https://github.com/MasayukiSuda/Mp4Composer-android/commit/a3687b6916ad2d959ff65fb637de153ad2fe7306
