### ISSUE TITLE
App Crash on flip video file

### ISSUE THREAD

**Issue by ParikshitTiwari** [MasayukiSuda/Mp4Composer-android#30]
java.lang.NumberFormatException: null
        at java.lang.Integer.parseInt(Integer.java:483)
        at java.lang.Integer.valueOf(Integer.java:611)
        at com.daasuu.mp4compose.composer.Mp4Composer.getVideoRotation(Mp4Composer.java:268)
        at com.daasuu.mp4compose.composer.Mp4Composer.access$200(Mp4Composer.java:25)
        at com.daasuu.mp4compose.composer.Mp4Composer$1.run(Mp4Composer.java:153)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

**Comment by MasayukiSuda** [comment]
fixed
