### ISSUE TITLE
have problem with null rotation

### ISSUE THREAD

**Issue by mikkipastel** [MasayukiSuda/Mp4Composer-android#31]
Hello,

I have problem with user cannot upload video because application crash with this

```
Fatal Exception: java.lang.NumberFormatException: null
       at java.lang.Integer.parseInt(Integer.java:483)
       at java.lang.Integer.valueOf(Integer.java:611)
       at com.daasuu.mp4compose.composer.Mp4Composer.getVideoRotation(Mp4Composer.java:268)
       at com.daasuu.mp4compose.composer.Mp4Composer.access$200(Mp4Composer.java:25)
       at com.daasuu.mp4compose.composer.Mp4Composer$1.run(Mp4Composer.java:153)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

and this is my code in kotlin

```
Mp4Composer(input, output)
                .rotation(Rotation.ROTATION_270)
                .size(720, 1280)
                .videoBitrate(4000 * 1000)
                .listener(object: Mp4Composer.Listener {
                    override fun onFailed(exception: Exception?) {
                        listener.onFailureRotation()
                        Log.d("onFailed rotate", exception.toString())
                    }

                    override fun onProgress(progress: Double) {
                        Log.d("onProgress rotate", (progress*100).toString())
                    }

                    override fun onCanceled() {
                        Log.d("onCanceled rotate", "onCanceled")
                    }

                    override fun onCompleted() {
                        Log.d("onCompleted rotate", "onCompleted()")
                        listener.onSuccessRotation()
                    }

                }).start() 
```

**Comment by MasayukiSuda** [comment]
fixed

**Comment by mikkipastel** [comment]
Hello, I try this for v0.1.8 with coding same README in kotlin code but have problem with some video

```
Fatal Exception: java.lang.RuntimeException: setDataSource failed: status = 0x80000000
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java)
       at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:69)
       at com.daasuu.mp4compose.composer.Mp4Composer.getVideoResolution(Mp4Composer.java:283)
       at com.daasuu.mp4compose.composer.Mp4Composer.access$300(Mp4Composer.java:24)
       at com.daasuu.mp4compose.composer.Mp4Composer$1.run(Mp4Composer.java:153)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:784)
```

**Comment by MasayukiSuda** [comment]
please upload video.

**Comment by mikkipastel** [comment]
Hello,

This is video file with problem https://drive.google.com/file/d/1HD6MmzHGTtci2HAU4uHwTlJR61de1jzX/view?usp=sharing

P.S. this is less video for have problem with use this library

**Comment by MasayukiSuda** [comment]
thx !

**Comment by MasayukiSuda** [comment]
Please try.
