### ISSUE TITLE
Not working on 1920x1080

### ISSUE THREAD

**Issue by 4ybakut2004** [MasayukiSuda/Mp4Composer-android#40]
I try to process a video with the resolution 1920x1080 captured from camera and has the error:
```
2019-02-09 19:21:33.761 11035-11704/ru.myapp.app E/ACodec:  configureCodec multi window instance fail  appPid : 11035
2019-02-09 19:21:33.765 11035-11704/ru.myapp.app E/ACodec: [OMX.qcom.video.decoder.avc] configureCodec returning error -5001
2019-02-09 19:21:33.765 11035-11704/ru.myapp.app E/ACodec: signalError(omxError 0x80001001, internalError -5001)
2019-02-09 19:21:33.765 11035-11703/ru.myapp.app E/MediaCodec: Codec reported err 0xffffec77, actionCode 0, while in state 3
2019-02-09 19:21:33.767 11035-11689/ru.myapp.app E/MediaCodec: configure failed with err 0xffffec77, resetting...
```

Mp4Composer.Listener.onFailed() called with Exception:
```
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1884)
        at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:97)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:104)
        at com.daasuu.mp4compose.composer.Mp4Composer$1.run(Mp4Composer.java:196)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:762)
```

It's all ok with the resolution 1280x720.
Samsung Galaxy J5.

**Comment by MasayukiSuda** [comment]
Samsung Galaxy J5. Does not support 1920x1080. Codec is impossible.
