### ISSUE TITLE
android.media.MediaCodec$CodecException: Error 0xfffffc0e

### ISSUE THREAD

**Issue by qinxianyuzou** [MasayukiSuda/Mp4Composer-android#53]
Hello, this error is reported when compressing the video.
Android Log：
`E/Mp4Composer: This devicel cannot codec with that setting. Check width, height, bitrate and video format.
    android.media.MediaCodec$CodecException: Error 0xfffffc0e
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:2023)
        at android.media.MediaCodec.configure(MediaCodec.java:1951)
        at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:81)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:107)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:268)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`

Your Log：
`D/Mp4Composer: rotation = 0
D/Mp4Composer: rotation = NORMAL
D/Mp4Composer: inputResolution width = 544 height = 962
 D/Mp4Composer: outputResolution width = 720 height = 1273
 D/Mp4Composer: fillMode = PRESERVE_ASPECT_FIT
D/Mp4Composer: bitrate=6874200`

**Comment by MasayukiSuda** [comment]
Your devicel cannot codec with that setting.
Perhaps the cause is `outputResolution width = 720 height = 1273.`

**Comment by qinxianyuzou** [comment]
> Your devicel cannot codec with that setting.
> Perhaps the cause is `outputResolution width = 720 height = 1273.`

Yes,  but I recommend Mp4Composer to provide verification.
My modification:
`        if ((outWidth & 1) == 1) {
            outWidth--
        }
        if ((outHeight & 1) == 1) {
            outHeight--
        }`

**Comment by MasayukiSuda** [comment]
Thank you for the suggestion. But the suggestion doesn't help, so try it differently.

**Comment by vinallathiya** [comment]
@MasayukiSuda  Issue related size:   after apply compression output video file size may get increased for some video then original video file size.

**Comment by tigerss** [comment]
This error will also show on some devices that don't support multiple codecs running at the same time. Example if we play a video at 1920x1080 then try to use Mp4Composer, you should first release the video player to clean up codec resources, then use Mp4Composer

**Comment by harrymash2006** [comment]
still an issue, did anyone got the solution ?
