### ISSUE TITLE
samsun j7 max FHD video watermark issue

### ISSUE THREAD

**Issue by nehaarya2003** [MasayukiSuda/Mp4Composer-android#54]
E/Mp4Composer: This devicel cannot codec with that setting. Check width, height, bitrate and video format.
    android.media.MediaCodec$CodecException: Error 0xffffec77
        at android.media.MediaCodec.native_configure(Native Method)
        at android.media.MediaCodec.configure(MediaCodec.java:1943)
        at android.media.MediaCodec.configure(MediaCodec.java:1872)
        at com.daasuu.mp4compose.composer.VideoComposer.setUp(VideoComposer.java:108)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:109)
        at com.daasuu.mp4compose.composer.Mp4Composer$1.run(Mp4Composer.java:234)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by MasayukiSuda** [comment]
Your devicel cannot codec with that setting. Check width, height, bitrate and video format.
Perhaps the cause is output video width and height.

**Comment by nehaarya2003** [comment]
Can you please help me regarding this not able to resolve

**Comment by Nam9988** [comment]
> Your devicel cannot codec with that setting. Check width, height, bitrate and video format.
> Perhaps the cause is output video width and height.

Thanks. how to get the maximum size the device supports
