### ISSUE TITLE
Multi Trim

### ISSUE THREAD

**Issue by VittoriDavide** [MasayukiSuda/Mp4Composer-android#56]
I was trying to do a multi trim of a video. I have a video of 60 sec and I wanted 6 of 10 secs. 

I tried to do the trimming of the video in parallel but is not working properly. I have to do it in sequence but is kind of slow, do you have any suggestion on how may I do this?

The Error that I am having is this

```
2019-11-27 11:47:48.640 26711-27167/com.puzio.fantamaster E/Mp4Composer: Unable to compose the engine
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_dequeueInputBuffer(Native Method)
        at android.media.MediaCodec.dequeueInputBuffer(MediaCodec.java:2569)
        at com.daasuu.mp4compose.composer.VideoComposer.drainExtractor(VideoComposer.java:175)
        at com.daasuu.mp4compose.composer.VideoComposer.stepPipeline(VideoComposer.java:130)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.runPipelines(Mp4ComposerEngine.java:242)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:126)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:268)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
2019-11-27 11:47:48.644 26711-27168/com.puzio.fantamaster E/Mp4ComposerEngine: Could not shutdown mediaExtractor, codecs and mediaMuxer pipeline.
    java.lang.IllegalStateException
        at android.media.MediaCodec.native_stop(Native Method)
        at android.media.MediaCodec.stop(MediaCodec.java:2067)
        at com.daasuu.mp4compose.composer.VideoComposer.release(VideoComposer.java:158)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:137)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:268)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)


```

**Comment by MasayukiSuda** [comment]
I can't understand what you are saying, so please write some concrete code.

**Comment by MasayukiSuda** [comment]
In the first place it is a mistake to try to trim video in parallel. You should devise to complete the trimming in one time.
