### ISSUE TITLE
How Can be Combine Both ExoPlayer Filters and Mp4Composer?

### ISSUE THREAD

**Issue by amitsharma492** [MasayukiSuda/Mp4Composer-android#7]
I am trying to show filters on Video on Real time  - Exoplayer is Perfect
Then I have to Apply that filter to video and save the new video - Mp4Composer Working Fine

Now I want to Combine both Solution How can do that?

I am getting error while doing so 

``Could not get attrib or uniform location for uMVPMatrix
  at com.daasuu.epf.filter.GlFilter.getHandle(GlFilter.java:219)
  at com.daasuu.epf.filter.GlFilter.setUpSurface(GlFilter.java:235)
  at com.daasuu.epf.composer.DecoderSurface.<init>(DecoderSurface.java:64)
  at com.daasuu.epf.composer.VideoComposer.setUp(VideoComposer.java:75)
  at com.daasuu.epf.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:103)
  at com.daasuu.epf.composer.Mp4Composer$1.run(Mp4Composer.java:160)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
  at java.lang.Thread.run(Thread.java:761)``

**Comment by MasayukiSuda** [comment]
not support.
