### ISSUE TITLE
Mp4Composer: Unable to compose the engine

### ISSUE THREAD

**Issue by HirenBharodiya** [MasayukiSuda/Mp4Composer-android#84]
Hello,

I'm apply GlWatermarkFilter on video Its work great, but some time I facing an error like this...

com.app_package E/Mp4Composer: Unable to compose the engine
    java.lang.IllegalStateException: writeSampleData returned an error
        at android.media.MediaMuxer.nativeWriteSampleData(Native Method)
        at android.media.MediaMuxer.writeSampleData(MediaMuxer.java:682)
        at com.daasuu.mp4compose.composer.MuxRender.writeSampleData(MuxRender.java:92)
        at com.daasuu.mp4compose.composer.RemixAudioComposer.drainEncoder(RemixAudioComposer.java:196)
        at com.daasuu.mp4compose.composer.RemixAudioComposer.stepPipeline(RemixAudioComposer.java:102)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.runPipelines(Mp4ComposerEngine.java:267)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:133)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by Ketuzzz** [comment]
I am facing this issue too. 

D/Mp4Composer: rotation = 0
D/Mp4Composer: rotation = NORMAL
D/Mp4Composer: inputResolution width = 360 height = 460
    outputResolution width = 360 height = 560
    fillMode = PRESERVE_ASPECT_FIT
    bitrate=1512000
W/FileSource: offset/length adjusted from 0/576460752303423487 to 0/1194906
E/Mp4Composer: Unable to compose the engine
    java.lang.RuntimeException: setDataSource failed: status = 0xFFFFFFEA
        at android.media.MediaMetadataRetriever.setDataSource(Native Method)
        at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:141)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:82)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
W/System: A resource failed to call close.

**Comment by dondell** [comment]
I got same issue
`10-24 23:44:50.726 26418-26893/com.daasuu.mp4composer E/Mp4Composer: Unable to compose the engine
    java.lang.IllegalStateException: Failed to stop the muxer
        at android.media.MediaMuxer.nativeStop(Native Method)
        at android.media.MediaMuxer.stop(MediaMuxer.java:242)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:149)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:312)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)
10-24 23:44:50.726 26418-26893/com.daasuu.mp4composer E/SAMPLE: onFailed() Failed to stop the muxer
`

**Comment by sanketk478** [comment]
same issue.

**Comment by dondell** [comment]
@sanketk478 You can use https://github.com/MasayukiSuda/GPUVideo-android/

**Comment by ranaaditya** [comment]
any update on this issue @MasayukiSuda ? I am also facing this issue !

Thanks !

**Comment by DoozyDoz** [comment]
I got the same issue when my video was too high res

**Comment by DoozyDoz** [comment]
> @sanketk478 You can use https://github.com/MasayukiSuda/GPUVideo-android/

doesnt solve it , I tried . the solution is to reduce the res (width, height)

**Comment by umairshah143** [comment]
![image](https://github.com/MasayukiSuda/Mp4Composer-android/assets/71061325/7af38cd0-ed6f-4942-9453-d613e0e10b53)
Facing same issue

**Comment by DannyFilo** [comment]
Same issue... Dear @MasayukiSuda are you planning to respond after 3 years ? or is this project abandoned ?
