### ISSUE TITLE
Issue when try to add speed or trim options

### ISSUE THREAD

**Issue by vksBhardwaj** [MasayukiSuda/Mp4Composer-android#85]
2020-10-13 13:38:32.329 6255-6869/com.matinet.dance E/Mp4Composer: Unable to compose the engine

    java.lang.RuntimeException: Could not determine actual output format.
        at com.daasuu.mp4compose.composer.VideoComposer.drainEncoder(VideoComposer.java:233)
        at com.daasuu.mp4compose.composer.VideoComposer.stepPipeline(VideoComposer.java:116)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.runPipelines(Mp4ComposerEngine.java:266)
        at com.daasuu.mp4compose.composer.Mp4ComposerEngine.compose(Mp4ComposerEngine.java:133)
        at com.daasuu.mp4compose.composer.Mp4Composer$2.run(Mp4Composer.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

**Comment by MrYZJ** [comment]
Did you solve this question? I also encountered this problem.Can you help me?

**Comment by vikas-shrma** [comment]
yes. i solved this issue

**Comment by mathislaurentpiquoti** [comment]
@vksBhardwaj How did you solve it ??? Please let us know
